githubRepoOwner: ejoffe
githubRepoName: spr
githubHost: github.com
requireChecks: true
requireApproval: false
githubRemote: origin
githubBranch: master
remoteBranches: []
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
branchNameIncludeTarget: false
